### ISSUE TITLE
CleanWebpackPlugin doesn't clean the output dir when it's outside the root dir 

### ISSUE THREAD

**Issue by ZindreX** [dolittle-tools/TypeScript.Webpack#1]
Could we have the same functionality as in this pull request:
https://github.com/dolittle-interaction/JavaScript.Build.Aurelia/issues/21

I think it should be added here:
https://github.com/dolittle-tools/TypeScript.Webpack/blob/273c8848181fb16c127d908250a05d2ed072f9e9/Source/Webpack/WebpackConfiguration.ts#L169

**Comment by woksin** [comment]
Cool, I did not actually know this. I will figure it out

**Comment by woksin** [comment]
I releases a patch that worked for me, can you confirm @ZindreX

Commit: https://github.com/dolittle-tools/TypeScript.Webpack/commit/23176bbd21bce87c15189aa037a0a197872389d5

**Comment by ZindreX** [comment]
Thanks, for the quick reply and fix!
Works for me too.
